DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS squat;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  trained TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  squat INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);